### ISSUE TITLE
golangci config file is missing

### ISSUE THREAD

**Issue by ccoVeille** [go-kod/kod#174]
The project should have a `.golangci.yml` or at least Taskfile.yml should use `golangci-lint run --no-config`

because the way golangci-lint works when looking for configuration files, if there is no golangci file in current project, it will try the parent folders. If there is one it would apply its settings

I do have this locally to be able to test random Go project with a full set of rules. my settings are way more restrictive than the default values.

_Originally posted by @ccoVeille in https://github.com/go-kod/kod/issues/149#issuecomment-2180921824_

**Comment by sysulq** [comment]
PR is welcome :-)

**Comment by ccoVeille** [comment]
Sure then I will @sysulq, could you assign me the ticket ?

Thanks

**Comment by ccoVeille** [comment]
You inspired me to create

https://github.com/ccoVeille/golangci-lint-config-examples

It's empty now, but you can star and watch
